[project]
name = "bbgpt"
version = "0.1.0"
description = "Karpathy's `Let's build GPT from scratch`"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=3.8.0",
    "torch>=2.4.1",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.5",
]
